# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sop_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1702, 1158)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.front_view = QtWidgets.QWidget()
        self.front_view.setObjectName("front_view")
        self.stackedWidget.addWidget(self.front_view)
        self.video_view = QtWidgets.QWidget()
        self.video_view.setObjectName("video_view")
        self.stackedWidget.addWidget(self.video_view)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.stats_frame = QtWidgets.QFrame(self.centralwidget)
        self.stats_frame.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.stats_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stats_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stats_frame.setObjectName("stats_frame")
        self.horizontalLayout.addWidget(self.stats_frame)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1702, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
